### ISSUE TITLE
Getting error while using the python script

### ISSUE THREAD

**Issue by marcelomanzo** [fbiego/ESP32_BLE_OTA_Arduino#13]
I am getting Error # 
without more details.

It does not flash it.

#####################################################################
    ------------------------BLE OTA update---------------------
    Arduino code @ https://github.com/fbiego/ESP32_BLE_OTA_Arduino
#####################################################################
Trying to start OTA update
Reading from:  firmware.bin
Transfer mode: 0
Progress: |██████████████████████████████████████████████████| 100.0% Complete
Installing firmware
OTA result:  Written : 160000/160000 [100%] 
Error #:
Waiting for disconnect... : Device disconnected

**Comment by marcelo-srs** [comment]
rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:10124
load:0x40080400,len:5828
entry 0x400806a8
Starting BLE OTA sketch
Characteristic defined! Now you can read it in your phone!
Connected
TX  AA 00 
TX  F1 00 01 
TX  F1 00 02 
TX  F1 00 03 
TX  F1 00 04 
TX  F1 00 05 
TX  F1 00 06 
TX  F1 00 07 
TX  F1 00 08 
TX  F1 00 09 
TX  F1 00 0A 
TX  F1 00 0B
TX  F1 00 0C
TX  F1 00 0D
TX  F1 00 0E
TX  F1 00 0F
TX  F1 00 10
TX  F1 00 11
TX  F1 00 12
TX  F1 00 13
TX  F1 00 14
TX  F1 00 15
TX  F1 00 16
TX  F1 00 17
TX  F1 00 18
TX  F1 00 19
TX  F1 00 1A
TX  F1 00 1B
TX  F1 00 1C 
TX  F1 00 1D 
TX  F1 00 1E 
TX  F1 00 1F 
TX  F1 00 20 
TX  F1 00 21 
TX  F1 00 22 
TX  F1 00 23 
TX  F1 00 24 
TX  F1 00 25 
TX  F1 00 26 
TX  F1 00 27 
TX  F2 00 28 
Trying to start update
Written : 161872 successfully
E (209034) esp_image: invalid segment length 0xffffffff
Error Occurred. Error #: 9
TX  0F 57 72 69 74 74 65 6E 20 3A 20 31 36 31 38 37 32 2F 31 36 31 38 37 32 20 5B 31 30 30 25 5D 20 0A 45 72 72 6F 72 20 23 3A 20 00     
Removing update file
Rebooting to complete OTA update
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:10124
load:0x40080400,len:5828
entry 0x400806a8
Starting BLE OTA sketch
Characteristic defined! Now you can read it in your phone!
