### ISSUE TITLE
I use in esp32 is work but in esp32-s3 in updater retun fail message 

### ISSUE THREAD

**Issue by ghost** [fbiego/ESP32_BLE_OTA_Arduino#24]

**Comment by emmt55s16** [comment]
hi,fbiego : 
I try to SD_Update example in ESP32 , ESP32-S3 , ESP32 can update success and run update code , but reset will go back to run SD_Update , ESP32-S3 will return error : E (1681) boot_comm: mismatch chip ID, expected 9, found 0 , the result is the same as before . I will change to eclipse + ESP-IDF and try to change sdkconfig , thanks 
![ESP32_001](https://user-images.githubusercontent.com/119062462/208344341-b1496d99-e431-45f7-868e-29aebe2eeef6.png)
![ESP32_002](https://user-images.githubusercontent.com/119062462/208344349-4aec447e-6f35-4edc-b379-f88aa32e3b6b.png)
![ESP32_003](https://user-images.githubusercontent.com/119062462/208344355-9d7c434b-c5f3-45fc-8251-afcd5fd6aa8e.png)
![ESP32_004](https://user-images.githubusercontent.com/119062462/208344363-b8ff3816-ed99-432d-a450-ab0fcfb4516f.png)
![ESP32_S3_001](https://user-images.githubusercontent.com/119062462/208344367-51a617f9-8697-46b0-904f-b06233b0d8b8.png)
