### ISSUE TITLE
Can't connect to the ESP32

### ISSUE THREAD

**Issue by HHavendano** [fbiego/ESP32_BLE_OTA_Arduino#25]
I try to use the code ,and the app. I can select the Firmware file, but i can select de device. 

1. I select the "Chose" button
2. Show me the name ESP32 OTA, and i select it.
3. I wait but nothing happen
4. After 5 seconds, the app closes.

So i can't update the ESP32 for that. Could you help me?

**Comment by fbiego** [comment]
I'm looking into this issue

**Comment by fbiego** [comment]
the app has been updated

**Comment by HHavendano** [comment]
Thanks but still doesn't work.  Select the device and show the esp32 and a few seconds the esp32 disconnect. I'ts about the app or my ESP32?

**Comment by fbiego** [comment]
What services and characteristics are broadcasted by ESP32?
You can use `nRF Connect` to view

**Comment by HHavendano** [comment]
![image](https://user-images.githubusercontent.com/108143953/221367202-79ab2a14-b162-4384-9d8d-0855c191425a.png)

**Comment by HHavendano** [comment]
I don't know what am i looking for

**Comment by fbiego** [comment]
Click on the 3 dots and refresh the services

**Comment by HHavendano** [comment]
![image](https://user-images.githubusercontent.com/108143953/221368008-90968fce-93d7-4d04-81cd-feebb4a5cd10.png)
Done

**Comment by fbiego** [comment]
https://github.com/fbiego/ESP32_BLE_OTA_Arduino/blob/fa90638f2997d7965880c2cd6aca1e9b05c83ba2/esp32_ble_ota/esp32_ble_ota.ino#L56-L58

This service should be listed, after that you can disconnect then use the OTA app

**Comment by HHavendano** [comment]
I see, now i can connect it.  now i try to upload the firmware, it downloaded ,but it show me Error# 9. What is it?

**Comment by HHavendano** [comment]
@fbiego What is the Error#9?

**Comment by fbiego** [comment]
#26
