### ISSUE TITLE
Error#9

### ISSUE THREAD

**Issue by HHavendano** [fbiego/ESP32_BLE_OTA_Arduino#26]
I trying to update the firmware ,but i recive the Error#9. and the esp32 start again. How can i fix it?

**Comment by fbiego** [comment]
What Flash are you using SPIFFS or FFat? also check that you have enough space to store the update file

**Comment by HHavendano** [comment]
Minimal SPIFFS, I wanted to adapted to another sketch that i used. OTA via HTTP. Is possible adapt both part on the same sketch?

**Comment by fbiego** [comment]
Minimal SPIFFS may not have enough space to store the update file. 
As for the OTA via HTTP, it may be challenging to implement both functionalities in the same sketch

**Comment by HHavendano** [comment]
Ok, thanks
